### ISSUE TITLE
Password is exposed in Windows clipboard history

### ISSUE THREAD

**Issue by thombet** [pwsafe/pwsafe#800] opened 2021-11-05 18:17 UTC
Hello, I would like report a bug with the "clear clipboard" feature and Windows 10's clipboard history.
Indeed when I double click a credential in Password Safe, the following message is displayed:
"Pressing OK will copy the password of the selected item to the clipboard. The clipboard will be securely cleared when Password Safe is closed."
Nevertheless when I open the clipboard history (with Win+V) the password can be seen in clear text and is not removed when Password Safe is closed.

It got this in Windows 10 20H2 and Password Safe v3.52

**Comment by TLCF** [comment] 2021-11-07 06:13
Same issue in Windows 10 21H1 and Password Safe V.57

**Comment by ronys** [comment] 2021-11-08 19:57
This appears to be due to the clipboard history feature added in Windows 10.
As a temporary workaround, you can disable the clipboard history via the Windows Settings->Clipboard menu.

**Comment by thombet** [comment] 2021-11-09 06:57
Thank you confirming the bug and the workaround.

Was the clearing of the clipboard history supported in previous versions of Windows and/or pwsafe?

**Comment by ronys** [comment] 2021-11-09 19:53
Clipboard History is a relatively recent addition to Windows, so no, this isn't a regression of existing PasswordSafe behavior, but rather a failure to track new Windows functionality for implications on PasswordSafe.

In any case, fixed in commit d11a82818, will be in next release.

**Closed by ronys** 2021-11-09 19:53 UTC

**Comment by thombet** [comment] 2021-11-09 21:41
Wow that was fast: thanks for fixing this!
