### ISSUE TITLE
System tray is missing in 1.16.1 when Wangard X server is used.

### ISSUE THREAD

**Issue by ykne** [pwsafe/pwsafe#958] opened 2023-05-04 02:11 UTC
builds Up to and including 1.16.0  work just fine but 1.16.1 produces rpm package with help and at least one other functionality missing and/or broken.
I am using my #543 mock-build.sh and now have to force 1.16.0 tag in git clone line.
Please update [README.LINUX.DEVELOPERS.md](https://github.com/pwsafe/pwsafe/blob/master/README.LINUX.DEVELOPERS.md) for 1.16.1.

**Comment by ronys** [comment] 2023-05-04 05:25
Can you be more specific? Better yet, a pull request would be much appreciated.

**Comment by ykne** [comment] 2023-05-04 12:32
More specific:
Following [README.LINUX.DEVELOPERS.md](https://github.com/pwsafe/pwsafe/blob/master/README.LINUX.DEVELOPERS.md) instructions for creating an RPM package for 1.16.1 results in no help module in package and no icon tray support. 1.16.0 works fine.

**Comment by ronys** [comment] 2023-05-06 08:52
Problem isn't with the instructions, but with a recent change to the cmake files that turned off building the help files by default.
You can either set the PWS_BUILD_HELP option to ON in cmake, or pull the master branch, where this has been changed in commit 524120d2b

**Comment by ronys** [comment] 2023-05-06 08:53
Not sure about the icon tray support. Reopening to follow up on this.

**Comment by ykne** [comment] 2023-05-06 17:39
Verified that 1.16.0 system tray is present in both cases, Xorg and Wangard while 1.16.1 only under Xorg system tray is present. 1.16.1 and in case of Wangard there is an error message in Options->System:
![image](https://user-images.githubusercontent.com/6250736/236638681-64e6f445-8738-46e5-b4a8-e59d2285b10e.png)
prerequisites for system tray in latest GNOME: install gnome-shell-extension-appindicator, enable it via gnome-extensions-app, relogin. Package names may slightly differ in different distributions. Currently testing in RHEL derivative, wx v3.0.5

**Comment by ronys** [comment] 2023-05-08 16:51
Closing this, as the system tray support seems to be an environment issue, rather than a regression in pwsafe.

**Closed by ronys** 2023-05-08 16:51 UTC

**Comment by ykne** [comment] 2023-05-10 18:49
Hello @ronys , I must disagree, let me repeat:

> Verified that 1.16.0 system tray is present in both cases, Xorg and Wangard while 1.16.1 only under Xorg system tray is present. 

I tried to glance over `git diff 1.16.0` output in an attempt to find something obvious but no luck.

**Comment by ykne** [comment] 2023-05-14 02:30
Error seems to come from this method:
https://github.com/pwsafe/pwsafe/blob/f3ad80a286c7755c1f8f7b81d35ee2b343e28577/src/ui/wxWidgets/wxUtilities.cpp#L191
