### ISSUE TITLE
PasswordSafe crashes upon startup when maxmruitems is zero

### ISSUE THREAD

**Issue by Kxeo** [pwsafe/pwsafe#1272] opened 2024-05-20 21:30 UTC
This annoying error keeps popping up every time I try to open PasswordSafe. And it doesn't even show itself unless I use the command instead. But even when I don't, it still doesn't open.

`/usr/include/c++/13.2.0/bits/stl_vector.h:1125: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = std::__cxx11::basic_string<wchar_t>; _Alloc =std::allocator<std::__cxx11::basic_string<wchar_t> >; reference = std::__cxx11::basic_string<wchar_t>&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.`

Currently, I run Garuda Linux. The kernel is Linux-Zen, and at version 6.8.9. 
KDE Plasma is at version 6.0.4.

And as for the error itself, I don't even know how I triggered it to start appearing.

**Comment by ronys** [comment] 2024-05-21 06:50
What version of PasswordSafe are you trying? Did you build it locally, e.g., using yay?

**Comment by Kxeo** [comment] 2024-05-21 10:59
> What version of PasswordSafe are you trying? 
1.18-2.
> Did you build it locally, e.g., using yay?
I didn't use yay, because that never works for me... I used makepkg -si.

**Comment by igor2x** [comment] 2024-05-21 15:15
@Kxeo, this may not be the way you would like, but can you test the Password Safe's [Flatpak version](https://flathub.org/apps/org.pwsafe.pwsafe) for [Garuda Linux.](https://wiki.garudalinux.org/en/how-to-flatpak)

**Comment by Kxeo** [comment] 2024-05-21 16:06
> @Kxeo, this may not be the way you would like, but can you test the Password Safe's [Flatpak version](https://flathub.org/apps/org.pwsafe.pwsafe) for [Garuda Linux.](https://wiki.garudalinux.org/en/how-to-flatpak)

Nope. That's literally the one I used when using PasswordSafe for the first time. It not working is the whole reason I switched to the AUR version.

**Comment by ronys** [comment] 2024-05-21 17:21
Sorry, I can't reproduce the crash on my Arch VM.
Can you build a debug version and provide a stack trace?

**Comment by Kxeo** [comment] 2024-05-21 17:48
`GNU gdb (GDB) 14.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/pwsafe...
Reading symbols from /usr/lib/debug//usr/bin/pwsafe.debug...
[?2004h(gdb) po[K[K[w[K[Kpwsafe
[?2004l
[?2004h(gdb) /usr[K[K[K[Krun /usr/bin/pwsafe
[?2004l
Starting program: /usr/bin/pwsafe /usr/bin/pwsafe

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
[?2004hEnable debuginfod for this session? (y or [n]) 
[?2004l
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff0e006c0 (LWP 262337)]
[New Thread 0x7fffebe006c0 (LWP 262338)]
[New Thread 0x7fffeb4006c0 (LWP 262339)]
[New Thread 0x7fffeaa006c0 (LWP 262340)]
[New Thread 0x7fffea0006c0 (LWP 262341)]

Thread 1 "pwsafe" received signal SIGABRT, Aborted.
0x00007ffff68a8e44 in ?? () from /usr/lib/libc.so.6
[?2004h[?2004l
[?2004h(gdb) `

Is this what you meant @ronys?

**Comment by ronys** [comment] 2024-05-22 11:02
Yes. Now type 'where' (without the quotes) in the (gdb) prompt. This should give a stack trace, which is what we need to find the crash location in our code.

**Comment by ronys** [comment] 2024-05-22 13:21
Aha!

This has nothing to do with the distro. You've triggered an old bug by setting the "Remember last N databases" to zero.

Yo can work around this by either manually editing the pwsafe.cfg file and changing 
        <maxmruitems>0</maxmruitems>
to a non-zero value, for example
        <maxmruitems>1</maxmruitems>
or just delete the pwsafe.cfg file, and PasswordSafe will generate on with default values.

A fix will be ready in a couple of days.

**Comment by Kxeo** [comment] 2024-05-22 13:49
> Aha!
> 
> This has nothing to do with the distro. You've triggered an old bug by setting the "Remember last N databases" to zero.
> 
> Yo can work around this by either manually editing the pwsafe.cfg file and changing 0 to a non-zero value, for example 1 or just delete the pwsafe.cfg file, and PasswordSafe will generate on with default values.
> 
> A fix will be ready in a couple of days.

Dang. So passwordsafe straight up just got murdered because I tried to do something that we forgot killed it.

**Comment by igor2x** [comment] 2024-05-23 08:33
I have also tested Password Safe v1.18.2 from flatpak on Ubuntu 22.04 and if I change Manage | Options | System | Remember last 0 databases and closing down program and reopen it from terminal:
`flatpak run org.pwsafe.pwsafe`

and Password Safe does not start at all, but instead outputs the error:

> /usr/include/c++/13.2.0/bits/stl_vector.h:1125: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = std::__cxx11::basic_string<wchar_t>; _Alloc = std::allocator<std::__cxx11::basic_string<wchar_t> >; reference = std::__cxx11::basic_string<wchar_t>&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.

After I deleted the flatpak's Password Safe file: 
/home/igor/.var/app/org.pwsafe.pwsafe/config/pwsafe/safe.cfg
and rerun a program and Password Safe starts successfully.

As expected this problem also affects flatpak version.

**Comment by ronys** [comment] 2024-05-23 18:12
Bug also affected Windows version.
Fixed in commit df70d48

**Closed by ronys** 2024-05-23 18:12 UTC
Labels: bug, Linux, Windows
