### ISSUE TITLE
Password expiry warning doesn't work [PasswordSafe Linux 1.13]

### ISSUE THREAD

**Issue by madmartin** [pwsafe/pwsafe#734] opened 2021-03-25 12:01 UTC
Hi,
since some time I changed from the pwsafe windows version (used on Linux with Wine) to the linux version, started with 1.11.
Now I discover that the warning about expired paswords does not work. 
The warning option is on, but all the passwords expiring within the time range (or already have expired) keep their green rectangle instead of turning yellow or red.
This feature has worked with the windows version I used previously.
The database version of the PW DB is 3.14.

I will try to help finding that in the source code, can someone give me some guidance where I find related code in the source?

BTW I am the maintainer of passwordsafe on Gentoo Linux. see  [here](https://packages.gentoo.org/packages/app-admin/passwordsafe)

**Comment by ronys** [comment] 2021-03-25 16:01
The problem is that this feature hasn't been implemented yet in the wx port, so it's a matter of porting the Windows implementation of CheckExpiredPasswords(), as well as the logic in the Tree control that colors them correctly.

Volunteers?

**Comment by madmartin** [comment] 2021-03-25 16:47
I can have a look, but dont give me more than 10% success rate....

**Comment by KaiZin2018** [comment] 2021-03-25 19:47
You might double check Windows
 int CCWTreeCtrl::GetEntryImage(const CItemData &ci) const
and wxWidgets
 void TreeCtrl::SetItemImage(const wxTreeItemId &node, const CItemData &item)
Be aware about ordering of the icons in xpmList.

May be I can help next week.

**Comment by madmartin** [comment] 2021-04-01 17:51
@KaiZin2018  and @ronys  - I tested your patch 65e4ea68e5 - it seems to work on my database - excellent!!!! 
Can you please arrange that this will be merged into the next release?

**Comment by ronys** [comment] 2021-04-02 05:45
Merged, will be in next release.

**Closed by ronys** 2021-04-02 05:45 UTC
