### ISSUE TITLE
Ubuntu 18.04: Exit by closing window does not remove lock file

### ISSUE THREAD

**Issue by ebeneezer1** [pwsafe/pwsafe#494] opened 2018-09-29 20:13 UTC
If I close PasswordSafe using the File>Exit menu item, all is well and the .plk file is removed.

But if I close PasswordSafe by closing the window ('X', top right), then it seems to leave the .plk file hanging around. Next time I open that PasswordSafe Database, I get a message that it is locked by me.

This is Ubuntu 18.04, using PasswordSafe 1.06 Beta.

**Comment by rafaelx** [comment] 2018-10-28 19:19
Not reproducable on Kubuntu and LMDE2. :)

**Comment by ebeneezer1** [comment] 2018-10-31 22:21
Thanks for looking into it. I am still seeing the problem - I'm not sure what info would be useful to you, but here are some versions from Settings > About:
Ubuntu 18.04.1 LTS
GNOME: 3.28.2
If there are any other pieces of info that might be useful, please let me know. Could it be gnome-specific?

**Comment by ebeneezer1** [comment] 2018-10-31 22:51
A little more... It appears that closing Password Safe (Ubuntu 18.04.1 GNOME 3.28.2) using the window close button is not terminating the pwsafe process (at least for me).

I can see this by running pwsafe from a terminal (/usr/bin/pwsafe). After closing the pwsafe window, the terminal does not return to the prompt, and looking at the running processes (via ps) I can see the /usr/bin/pwsafe process is still present. If I hit Ctrl+C to terminate pwsafe in the terminal, the .plk file is removed. 

If I run pwsafe from a terminal and close via File menu - Exit, the process does terminate.

**Comment by rafaelx** [comment] 2018-11-03 14:16
Another Ubuntu version another try. Means, I have installed Ubuntu 18.04.01 LTS (64 bit) with Gnome 3.28.2 to be as close as possible to the author's setup, but still I'm not able to reproduce the behavior.

In my case whenever I close the application via its close icon (the 'X' at top right of applications main window) the plk file always disappears.

If I terminate the application on the terminal via Ctrl-C the plk file is also removed.

If I start the application from the terminal and close it via the 'X' icon, the plk disappears and I get immediately back the prompt and no dangling pwsafe process remains.

Inspiried by dskrvk's comment I logged out and logged in again. In this case the plk file remained while the application was not present anymore. Question is which signal does the application receive on logout? What I know from bug report [1242](https://sourceforge.net/p/passwordsafe/bugs/1242/) is that in case of a received SIGHUB the plk file will also not be removed.

**Comment by ebeneezer1** [comment] 2018-11-05 21:42
Think I may have found the issue by looking at the code in PasswordSafeFrame::OnCloseWindow.

I had the "Put icon in System Tray" option turned on in my Options. If I turn off this option, closing the window removes the .plk file and the pwsafe process exits.

I'm happy for now - I'll leave it with you to decide whether to close this issue, or if something can be done to disable/hide the system tray options in code. PWSafe is detecting the presence of system tray support because I see the message "There appears to be no system tray support in your current environment" in my options.

Thanks again.

**Comment by rafaelx** [comment] 2018-11-05 23:05
Oh, I see. You stumbled over this annoying system tray [bug](https://sourceforge.net/p/passwordsafe/bugs/1443/), due to which I have "Put icon in System Tray" option always turned off. That's why I was not able to reproduce this issue. - Well, now I have two Ubuntu installations, beside my main OS. :)

The option could be disabled, but it could still be helpful for someone who has a config file which enables the applications system tray icon.

**Closed** 2018-11-11 17:02 UTC
