### ISSUE TITLE
[wx] Modernization of Password Setup Dialog

### ISSUE THREAD

**Issue by rafaelx** [pwsafe/pwsafe#1277] opened 2024-05-27 20:48 UTC
This ticket/issue was created to track and discuss the changes to the password setup dialog.
![SetupPassword](https://github.com/pwsafe/pwsafe/assets/4042917/136ebf7b-a9cd-4e30-bad9-eae464d523bd)

Related to #1197, #1273, #1274

**Comment by igor2x** [comment] 2024-05-31 15:40
I have downloaded latest master v19.1-pre from Github/Artifacts and installed it on Ubuntu 22.04. Because few of the PRs were merged lately I think it is fine to show how current dialog looks like. Changes to the picture from first post:
- title bar renamed
- field names changed from left to top of field
- eye icon right of field
- buttons where better grouped
- virtual keyboard icon added to the bottom-right of dialog
- I can no longer see icons on buttons, but this may be my machine specifics

![image](https://github.com/pwsafe/pwsafe/assets/10895030/6e0a2fb9-6d7d-4a31-959f-3c3f970b5962)

**Comment by igor2x** [comment] 2024-05-31 16:20
**1. Issue:** Dialog can be resized beyond minimal, so buttons gets hidden and interesting last sentence from the text above fields gets hidden also.

I retested on v1.18.2/flatpak and dialog can't be resized bellow minimal. This issue is regression in v1.19-pre.

![image](https://github.com/pwsafe/pwsafe/assets/10895030/adc06bf1-6849-44db-b05f-989270cb66d9)

**2. Simplification:** In my humble opinion text above dialog is way too long and complicated. First two sentences can be combined into: "The Master Password will be used to encrypt new password database file."

The last sentence from original text, we are basically saying there are no restrictions, you can use what ever you want. But in this case, why would you want to tell user that he or she can uses anything what she wants. I think last sentence should be removed.

Think little bit more, isn't word "encrypt" to technical? UX guidelines requires to remove technical jargon from dialogs. Average user doesn't know what encryption is. User should be capable of using program without knowing technical terms like encryption. Technical language belongs to documentation. My suggestion is to replace word "encrypt" with "lock". **Suggested text:** "The Master Password will be used to lock new password database file."

We can simplify text to look like this:
![image](https://github.com/pwsafe/pwsafe/assets/10895030/1b0c94f1-5acc-48d8-9513-5a16e38bb283)

**Closed** 2024-05-31 16:20 UTC
Labels: wx
