### ISSUE TITLE
Uncommitted new entries can be lost after database auto-lock when auto-read-only is enabled

### ISSUE THREAD

**Issue by kappa7194** [pwsafe/pwsafe#59] opened 2016-01-12 10:47 UTC
How to reproduce
1. Enable the “Open database read-only by default” option (“System” tab);
2. Enable the “Lock password database after” option (“Security” tab);
3. Open a database in read-write;
4. Open the “Add entry” dialog and fill it without committing (do not click “OK”);
5. Wait for the auto-lock timeout to expire and PasswordSafe to minimize;
6. Reopen PasswordSafe and unlock it — don't touch the “Open as read-only” checkbox;
7. Click the “OK” button to save the entry you were adding;
8. Notice that the entry has not been added to the database;
9. Weep.

The problem lies in steps 6 and 7: if you don't notice — or remember to unckeck — the “Open as read-only” checkbox, when you unlock the database you're shown the entry you were adding before the database auto-locked and you're allowed to “save” the entry by clicking the “OK” button, however since the database is now read-only the saving of the entry fails silently and its information is lost.

This probably applies to entries editing too (or any other kind of change which can be in an “uncommited” state).

I think this problem could be prevented in two different ways (I don't know if either is feasible though):
- don't allow the database to be unlocked as read-only if there are changes pending changes;
- don't allow the user to “OK” the “Add entry” dialog if the database has been unlocked in read-only ode;
- ask the user to switch the database in read-write when he tries to “OK” the “Add entry” dialog;

I think the third solution would be the better from a UX point and — possibly — the easiest one code-wise.

**Comment by vossenjp** [comment] 2016-05-01 20:40
The problem is worse than this.  If you open a DB in Read-only, forget, and make **any** change it is silently discarded!  At least it just was in 0.97 when I tested (not using 0.98 as noted in #90).

Steps to reproduce:
1. Close PWS
2. Open DB in read-only
3. Create a test entry and click "OK"
4. Test entry silently discarded!
5. Edit an existing entry and make a change
6. Create a test entry and click "OK"
7. Test change silently discarded!

**Comment by kappa7194** [comment] 2016-05-04 08:29
>The problem is worse than this.

I don't know if the issues are related, my issue is about the Windows GUI (I don't know if and how much code shares with the Linux one).

**Comment by ronys** [comment] 2016-05-10 19:27
Windows version fixed in commit 2180aa3 by disabling the ability to turn on read-only when unlocking a database with changes pending.

**Comment by dskrvk** [comment] 2016-10-02 16:43
This is what happens for me (v.0.99 wxWidgets, Ubuntu 15.10):

1. Open database in r/w mode.
2. Create new entry without clicking OK.
3. Wait for auto-lock with the entry window open.
4. Reopen database.
5. New entry is not in the tree, and the edit window is gone too.
6. Application is unable to open any further child windows, doesn't react to close, tray menu commands, or shortcuts. The only thing I can do is move the cursor in the tree view.

I don't have "open in read-only by default" enabled.

As discussed in https://github.com/pwsafe/pwsafe/issues/92, I had to modify the .deb file to use libwxgtk3.0-0v5 instead of libwxgtk3.0-0.

**Comment by rafaelx** [comment] 2018-10-28 20:12
> The problem is worse than this. If you open a DB in Read-only, forget, and make **any** change it is silently discarded! At least it just was in 0.97 when I tested (not using 0.98 as noted in #90).
> 
> Steps to reproduce:
> 
> 1. Close PWS
> 2. Open DB in read-only
> 3. Create a test entry and click "OK"
> 4. Test entry silently discarded!
> 5. Edit an existing entry and make a change
> 6. Create a test entry and click "OK"
> 7. Test change silently discarded!

In version 1.06BETA it is not possible to create a new item if DB is read-only. Additionally, there is no "OK" button shown in Edit/View dialog. The user can only close the dialog via "Close" button, so it should be quite obvious to the user that its modifications won't be applied.

**Comment by dskrvk** [comment] 2018-10-31 01:18
Just tested in 1.06, Ubuntu Gnome 18.04. The Edit window stays open even after the database lock and maintains all entered values. After reopening the DB I can successfully save the entry. This behavior seems acceptable - even though it's possible to see the entry contents with a locked DB, presumably the entry is not used yet, and any secrets can be regenerated.

**Closed** 2018-11-11 17:01 UTC
